import "./globals.css";

import { AntdRegistry } from "@ant-design/nextjs-registry";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ReduxProvider from "./StoreProvider";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body>
          <ToastContainer position="top-center" />

          <AntdRegistry>{children}</AntdRegistry>
        </body>
      </ReduxProvider>
    </html>
  );
}
